### ISSUE TITLE
Newer versions of OpenSSH do not allow scp to ntp200 or ntp250

### ISSUE THREAD

**Issue by Trax-** [centerclick/feedback#104] opened 2023-10-25 16:33 UTC
Not sure if this is a feature request or a bug.
Using version OpenSSH_for_Windows_9.4p1, LibreSSL 3.7.3 was unable to scp my certificate files to the NTP device.
After much searching was able to find an older version that worked (OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3)
the error message received when using the newer version was: C:\Program Files\OpenSSH\scp.exe: Received message too long 1315925549

**Comment by dave4445** [comment] 2023-10-25 18:56
Please try with the `-O` option to force scp not sftp.  See https://www.man7.org/linux/man-pages/man1/scp.1.html

**Comment by Trax-** [comment] 2023-10-25 19:07
Yes that appears to work thank you.

**Comment by dave4445** [comment] 2024-03-07 13:45
Duplicate of #69

**Closed as completed by dave4445** 2024-03-07 13:45 UTC
Labels: documentation, duplicate
